language: java

before_install: 
  - sudo apt-get update -qq 
  - sudo apt-get install oracle-java8-installer 

install: 
  - mvn install -Dmaven.compiler.target=1.8 -Dmaven.compiler.source=1.8 -DskipTests=true

script: 
  - mvn clean test -P dev
  - mvn clean verify -P integration-test
