-- CREATE TABLE filme (
--   id BIGINT,
-- 	nome varchar(255) not null,
-- 	descricao varchar(1000) not null,
-- 	capa varchar(255) not null,
-- 	PRIMARY KEY (id)
-- );
--
-- insert into filme
--   (id, nome, descricao, capa)
-- VALUES (
--   1,
--   'Jogos Vorazes: A Esperança - Parte 2',
--   'Após sobreviver por duas vezes aos Jogos Vorazes, Katniss Everdeen (Jennifer Lawrence) servirá como símbolo de uma revolução iniciada no Distrito 13.',
--   'http://cuzcuzliterario.com.br/wp-content/uploads/2014/02/1604682_676106875745982_1511978477_n_zpsb5bb0db1.jpg'
-- );
--
-- insert into filme
-- (id, nome, descricao, capa)
-- VALUES (
--   2,
--   'A Culpa é das Estrelas',
--   'Diagnosticada com câncer, a adolescente Hazel Grace Lancaster (Shailene Woodley) se mantém viva graças a uma droga experimental.',
--   'http://br.web.img1.acsta.net/r_640_600/b_1_d6d6d6/pictures/14/01/23/14/12/101764.jpg'
-- );
--
-- insert into filme
-- (id, nome, descricao, capa)
-- VALUES (
--   3,
--   'Hoje Eu Quero Voltar Sozinho',
--   'Leonardo (Guilherme Lobo), um adolescente cego, tenta lidar com a mãe superprotetora ao mesmo tempo em que busca sua independência.',
--   'http://br.web.img1.acsta.net/r_640_600/b_1_d6d6d6/pictures/14/02/28/15/07/507995.jpg'
-- );
-- 
-- insert into filme
-- (id, nome, descricao, capa)
-- VALUES (
--   4,
--   'O Poderoso Chefão',
--   'Don Vito Corleone (Marlon Brando) é o chefe de uma "família" de Nova York que está feliz, pois Connie (Talia Shire), sua filha, se casou com Carlo (Gianni Russo). ',
--   'http://br.web.img1.acsta.net/r_640_600/b_1_d6d6d6/medias/nmedia/18/90/93/20/20120876.jpg'
-- );
--
-- insert into filme
-- (id, nome, descricao, capa)
-- VALUES (
--   5,
--   'Um Sonho de Liberdade',
--   'Em 1946, Andy Dufresne (Tim Robbins), um jovem e bem sucedido banqueiro, tem a sua vida radicalmente modificada ao ser condenado por um crime que nunca cometeu, o homicídio de sua esposa e do amante dela.',
--   'http://br.web.img3.acsta.net/r_640_600/b_1_d6d6d6/medias/nmedia/18/90/16/48/20083748.jpg'
-- );